wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: huggingface
    huggingface_version: 2.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.7.6
      5: 0.10.20
      6: 2.5.1
      8:
      - 5
cv_valid:
  desc: null
  value: 0
data_dir:
  desc: null
  value: ../data
data_type:
  desc: null
  value: hieve
debug:
  desc: null
  value: true
downsample:
  desc: null
  value: 0.08
epochs:
  desc: null
  value: 10
eval_step:
  desc: null
  value: 1
eval_type:
  desc: null
  value: one
finetune:
  desc: null
  value: false
hieve_mlp_size:
  desc: null
  value: 64
hieve_threshold:
  desc: null
  value: -0.6
intersection_temp:
  desc: null
  value: 0.0001
lambda_anno:
  desc: null
  value: 1.0
lambda_cross:
  desc: null
  value: 0.0
lambda_pair:
  desc: null
  value: 1.0
lambda_trans:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 0.095
load_model:
  desc: null
  value: 0
log_batch_size:
  desc: null
  value: 7
loss_type:
  desc: null
  value: 0
lstm_hidden_size:
  desc: null
  value: 256
lstm_input_size:
  desc: null
  value: 768
matres_mlp_size:
  desc: null
  value: 32
matres_threshold:
  desc: null
  value: -0.5
max_grad_norm:
  desc: null
  value: 5.0
mlp_output_dim:
  desc: null
  value: 32
mlp_size:
  desc: null
  value: 32
model:
  desc: null
  value: box
model_save:
  desc: null
  value: 0
no_cuda:
  desc: null
  value: false
no_valid:
  desc: null
  value: false
num_layers:
  desc: null
  value: 1
patience:
  desc: null
  value: 8
proj_output_dim:
  desc: null
  value: 32
roberta_hidden_size:
  desc: null
  value: 1024
save_plot:
  desc: null
  value: 1
saved_model:
  desc: null
  value: /Users/ehwang/PycharmProjects/CE2ERE/src/model/matres_20210505163300_2ya6wb7v.pt
seed:
  desc: null
  value: 0
symm_eval:
  desc: null
  value: 0
symm_train:
  desc: null
  value: 0
volume_temp:
  desc: null
  value: 1.0
wandb_id:
  desc: null
  value: hwang7520/CE2ERE-src/2ya6wb7v
